/*
 * Frangipani genome annotation server that connects to genome storage servers
 * via the GA4GH API.
 * @author Ron Ammar
 */

var express= require("express");
var routes= require("./frangipani_node_modules/routes");
var dbFunctions= require("./frangipani_node_modules/mongodb_functions");


/* Command line options */
var opts= require("nomnom")
	.option("portNumber", {
		abbr: "p",
		full: "port",
		default: 8080,
		help: "User-specifed port number"
	})
	.parse();
console.log("Server running on port " + opts.portNumber);


/* Initialize the server. */
var app= express();


/* Connect to the DB. */
dbFunctions.connectAndInitializeDB();


/* Serve static content (css files, js files, templates, etc) from the
 * foundation directory. */
app.use(express.static("foundation-5.4.6", {index: false}));

app.get("/", function(request, response) {
	response.sendFile("foundation-5.4.6/frangipani.html", {root: "."});
});

app.use("/datasets", routes.getRouter);
app.use("/callsets/search", routes.postRouter);
app.use("/variants/search",routes.postRouter);

app.listen(opts.portNumber);

/* Listen for SIGINT events. These can be generated by typing CTRL + C in the 
 * terminal. */
process.on("SIGINT", function(){
	console.log("\nReceived interrupt signal. Closing connections to DB...");
	dbFunctions.closeConnection(function() {
		console.log("Bye!");
		process.exit(0);
	});
});