module.exports = {
	"INSTITUTION": "The Hospital for Sick Children",
	"MAX_RECORDS": 500,
	"ANNOVAR_ANNOTATIONS": {
		"snp138":{"usage":"f","index":false},
		"1000g2014sep_all":{"usage":"f","index":true},
		"1000g2014sep_amr":{"usage":"f","index":false},
		"1000g2014sep_eur":{"usage":"f","index":false},
		"1000g2014sep_sas":{"usage":"f","index":false},
		"1000g2014sep_eas":{"usage":"f","index":false},
		"1000g2014sep_afr":{"usage":"f","index":false},
		"esp6500_all":{"usage":"f","index":true},
		"cg69":{"usage":"f","index":true},
		"clinvar_20140929":{"usage":"f","index":false},
		"ljb26_all":{"usage":"f","index":false},
	},
	"FOOTER": "Report generated by Frangipani.",
	"DISCLAIMER_PREFIX": "This data is provided 'as is', 'where is' and without any express or implied warranties, including, but not limited to, any implied warranties of merchantability and/or fitness for a particular purpose. In no event shall ",
	"DISCLAIMER_SUFFIX": ", nor its agents, employers or representatives be liable for any direct, indirect, incidental, special, exemplary, or consequential damages (including, but not limited to, procurement of substitute goods or services; loss of use, data, or profits; or business interruption) however caused and on any theory of liability, whether in contract, strict liability, or tort (including negligence or otherwise) arising in any way or form out of the use of this data, even if advised of the possibility of such damage. All users assume the risk and responsibility for the accuracy, completeness or usefulness, or lack thereof, of any information, apparatus, product or process disclosed or that the use hereof would or would not infringe the rights of any other party.",
	"DISCLAIMER": ""
}